import libs = catch2%lib{catch2}
import libs += libcppzmq%lib{cppzmq}

exe{unit_tests}: {hxx cxx}{*} $libs

out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

cxx.poptions += "-I$out_pfx_src" "-I$src_pfx_src"

# Don't install private headers.
{hxx ixx}{*}: install = false
